source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ILMovieDB Example'
workspace '../ILMovieDB'

inhibit_all_warnings!

def import_pods
  pod 'AFNetworking', '~> 2.5.0'
  pod 'ILMovieDB', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'ILMovieDB Example'
  import_pods
end
