xcodeproj 'ILTMDb Example'
workspace '../ILTMDb'

inhibit_all_warnings!

def import_pods
  pod 'AFNetworking', '~> 1.3.0'
  pod 'ILTMDb', :path => '../'
end

target :ios do
  platform :ios, '6.0'
  link_with 'ILTMDb Example'
  import_pods
end
