source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ILMovieDB Tests'
workspace '../ILMovieDB'

inhibit_all_warnings!

def import_pods
  pod 'Expecta', '~> 0.2.1'
  pod 'AFNetworking', '~> 2.5.0'
  pod 'ILMovieDB', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'Tests'
  import_pods
end
